# Generated by Django 6.0.1 on 2026-01-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('IT_ADMIN', 'IT Admin'), ('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant'), ('SALES', 'Sales'), ('MARKETING', 'Marketing')], default='SALES', max_length=20),
        ),
    ]
