# Generated by Django 6.0.1 on 2026-01-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 4217 Code (e.g. USD)', max_length=3, unique=True)),
                ('symbol', models.CharField(help_text='Currency Symbol (e.g. $)', max_length=5)),
                ('name', models.CharField(help_text='Full Name (e.g. US Dollar)', max_length=50)),
                ('is_base', models.BooleanField(default=False, help_text='Is this the base reporting currency? (Usually CAD)')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Effective rate date')),
                ('rate_to_base', models.DecimalField(decimal_places=4, help_text='Conversion rate to Base Currency', max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='currencies.currency')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
