# Generated by Django 5.2.10 on 2026-01-27 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_address_family_client_allergies_and_more'),
        ('invoices', '0002_initial'),
        ('tours', '0002_tourbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='client',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='tour_instance',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.paymentmethod'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='clients.client'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='tour_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='tours.tourbooking'),
        ),
    ]
