# Generated by Django 5.2.10 on 2026-01-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoice_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (No Deposit)'), ('DEPOSIT', 'Deposit Paid'), ('INVOICED', 'Invoiced'), ('PAID', 'Paid in Full'), ('CANCELLED', 'Cancelled'), ('MOVED', 'Moved'), ('SPLIT', 'Split'), ('PENALTY', 'Penalty'), ('SUBMITTED', 'Submitted for Audit'), ('NEEDS_FIX', 'Needs Fix'), ('VERIFIED', 'Verified')], default='DRAFT', max_length=20),
        ),
    ]
