# Generated by Django 5.2.10 on 2026-01-28 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '__first__'),
        ('clients', '0002_address_family_client_allergies_and_more'),
        ('documents', '__first__'),
        ('flights', '0002_flightticket_client_flightticket_first_name_and_more'),
        ('invoices', '0004_invoice_amount_paid_alter_invoice_status'),
        ('tours', '0003_tourbooking_room_type_tourinstance_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddonService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('default_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='external_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_invoices', to='agents.agent'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='group_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='has_flight_intinerary',
            field=models.BooleanField(default=False, help_text='Client itinerary must be confirmed (flight info required)'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('ZH', 'Mandarin'), ('MX', 'Cantonese')], default='ZH', max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supporting_documents',
            field=models.ManyToManyField(blank=True, related_name='invoices', to='documents.supportingdocument'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tag',
            field=models.CharField(blank=True, choices=[('AUDIT_SUBMITTED', 'Audit Submitted'), ('VERIFIED', 'Verified'), ('NEEDS_FIX', 'Needs Fix'), ('CLARIFY', 'Clarify')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='flight_ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.flightticket'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='tour_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tourbooking'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='addon_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.addonservice'),
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Numeric value only', max_digits=10)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('date_used', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='clients.client')),
                ('invoice_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_coupons', to='invoices.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.coupon'),
        ),
    ]
