# Generated by Django 5.2.10 on 2026-02-04 13:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_travelgroup_remove_client_family_and_more'),
        ('invoices', '0005_addonservice_invoice_created_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='invoice',
            name='booking_number',
            field=models.CharField(default='BK-DEFAULT', help_text='Mandatory Booking Reference', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Generated when status is INVOICED or PAID', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (No Deposit)'), ('DEPOSIT', 'Deposit Paid'), ('INVOICED', 'Invoiced'), ('PAID', 'Paid in Full'), ('CANCELLED', 'Cancelled'), ('MOVED', 'Moved'), ('SPLIT', 'Split'), ('PENALTY', 'Penalty')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('FULL_PAYMENT', 'Full Payment'), ('PAYMENT', 'Payment')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoices.invoice')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.paymentmethod')),
            ],
        ),
    ]
