# Generated by Django 5.2.11 on 2026-02-06 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
        ('invoices', '0006_remove_invoice_amount_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='booking_number',
            field=models.CharField(help_text='Mandatory Booking Reference', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='external_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_invoices', to='agents.agent', verbose_name='Agency'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='sales_agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Sales'),
        ),
    ]
