# Generated by Django 5.2.10 on 2026-02-06 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoice_booking_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicepayment',
            name='payment_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('BALANCE', 'Balance'), ('FULL_AMOUNT', 'Full Amount')], max_length=20),
        ),
    ]
