# Generated by Django 5.2.10 on 2026-02-06 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_travelgroup_remove_client_family_and_more'),
        ('invoices', '0009_alter_invoiceitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_type',
            field=models.CharField(blank=True, choices=[('COUPON', 'Coupon'), ('DISCOUNT', 'Discount'), ('OTHER', 'Other')], default='COUPON', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Numeric value only', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('USED', 'Used'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20, null=True),
        ),
    ]
