# Generated by Django 5.2.10 on 2026-02-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_alter_invoice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='tag',
            field=models.CharField(blank=True, choices=[('AUDIT_SUBMITTED', 'Audit Submitted'), ('VERIFIED', 'Verified'), ('NEEDS_FIX', 'Needs Fix'), ('RECORD_ONLY', 'Record Only')], max_length=20, null=True),
        ),
    ]
