# Generated by Django 6.0.1 on 2026-01-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_code', models.CharField(help_text='e.g. AC, BR', max_length=3)),
                ('flight_number', models.CharField(help_text='e.g. 009', max_length=4)),
                ('departure_date', models.DateField()),
                ('departure_airport', models.CharField(help_text='e.g. YVR, YYZ', max_length=3)),
                ('arrival_airport', models.CharField(help_text='e.g. TPE, NRT', max_length=3)),
                ('airline_name', models.CharField(blank=True, max_length=100)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('cabin_class', models.CharField(choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First')], default='Economy', max_length=20)),
                ('meal_plan', models.CharField(blank=True, help_text='e.g. Vegetarian, Standard', max_length=50)),
                ('bags', models.IntegerField(default=1)),
                ('ticket_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flights.flight')),
            ],
        ),
    ]
