# Generated by Django 5.2.10 on 2026-01-27 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_address_family_client_allergies_and_more'),
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightticket',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='clients.client'),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='flightticket',
            name='pnr',
            field=models.CharField(blank=True, help_text='Passenger Name Record', max_length=20),
        ),
        migrations.AlterField(
            model_name='flightticket',
            name='seat_number',
            field=models.CharField(default='TBA', help_text='Specific seat or TBA', max_length=10),
        ),
    ]
