# Generated by Django 5.2.10 on 2026-02-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_alter_flight_airline_alter_flight_arrival_airport_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightinstance',
            old_name='unique_code',
            new_name='flight_code',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='airline_name',
        ),
        migrations.AlterField(
            model_name='airline',
            name='name',
            field=models.CharField(blank=True, help_text='e.g. Air Canada', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(blank=True, help_text='e.g. Vancouver International Airport', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='flightinstance',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightinstance',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightinstance',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightticket',
            name='bags',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='flightticket',
            name='cabin_class',
            field=models.CharField(blank=True, choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flightticket',
            name='seat_number',
            field=models.CharField(blank=True, help_text='Specific seat or TBA', max_length=10, null=True),
        ),
    ]
