# Generated by Django 6.0.1 on 2026-01-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=3, verbose_name='Country (3)')),
                ('days_count', models.CharField(max_length=2, verbose_name='Days (2)')),
                ('unique_seq', models.CharField(max_length=3, verbose_name='Unique Seq (3)')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('instance_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('total_spots', models.PositiveIntegerField(default=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='tours.product')),
            ],
        ),
    ]
