# Generated by Django 5.2.10 on 2026-01-27 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(help_text='e.g. JPN06...-S-01', max_length=50, unique=True)),
                ('booking_type', models.CharField(choices=[('SINGLE', 'Single Room'), ('DOUBLE', 'Double Room'), ('UPGRADE', 'Upgrade Class'), ('INFANT', 'Infant'), ('OTHER', 'Other')], default='DOUBLE', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Specific price for this booking unit', max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('HELD', 'Held')], default='AVAILABLE', max_length=20)),
                ('tour_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tours.tourinstance')),
            ],
        ),
    ]
