# Generated by Django 6.0.1 on 2026-01-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.AddField(
            model_name='product',
            name='country_code',
            field=models.CharField(default='JPN', max_length=3, verbose_name='Country (3)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='days_count',
            field=models.CharField(default='06', max_length=2, verbose_name='Days (2)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='unique_seq',
            field=models.CharField(default='001', max_length=3, verbose_name='Unique Seq (3)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourinstance',
            name='instance_code',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
