# Generated by Django 5.2.10 on 2026-01-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tourbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='room_type',
            field=models.CharField(blank=True, help_text='Specific room info e.g. Twin, Single, Special', max_length=50),
        ),
        migrations.AddField(
            model_name='tourinstance',
            name='language',
            field=models.CharField(choices=[('C', 'Chinese'), ('M', 'Mandarin'), ('E', 'English'), ('O', 'Other')], default='M', max_length=2),
        ),
    ]
