# Generated by Django 5.2.11 on 2026-02-06 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_tourbooking_room_type_tourinstance_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='days_count',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Days (2)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unique_seq',
            field=models.CharField(max_length=2, verbose_name='Unique Seq (2)'),
        ),
    ]
