# Generated by Django 5.2.10 on 2026-02-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_product_days_count_alter_product_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='booking_id',
            field=models.CharField(blank=True, help_text='e.g. JPN06...-S-01', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single Room'), ('DOUBLE', 'Double Room'), ('UPGRADE', 'Upgrade Class'), ('INFANT', 'Infant'), ('OTHER', 'Other')], default='DOUBLE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Specific price for this booking unit', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='status',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('BOOKED', 'Booked'), ('HELD', 'Held')], default='AVAILABLE', max_length=20),
        ),
    ]
