# Generated by Django 5.2.10 on 2026-02-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_tourbooking_booking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourinstance',
            name='instance_code',
        ),
        migrations.AddField(
            model_name='tourinstance',
            name='tour_code',
            field=models.CharField(default='LEGACY-TOUR-001', help_text='Format: JPN26A06H4 (Country+YY+M+DD+Seq)', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourinstance',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourinstance',
            name='language',
            field=models.CharField(blank=True, choices=[('C', 'Chinese'), ('M', 'Mandarin'), ('E', 'English'), ('O', 'Other')], default='M', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='tourinstance',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='tourinstance',
            name='total_spots',
            field=models.PositiveIntegerField(blank=True, default=20, null=True),
        ),
    ]
