# Generated by Django 5.2.10 on 2026-02-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_remove_tourinstance_instance_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourbooking',
            name='booking_type',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Single Room'), ('DOUBLE', 'Double Room'), ('TWIN', 'Twin Room'), ('UPGRADE', 'Upgrade Class'), ('INFANT', 'Infant'), ('OTHER', 'Other')], default='DOUBLE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tourinstance',
            name='language',
            field=models.CharField(blank=True, choices=[('C', 'Cantonese'), ('M', 'Mandarin'), ('E', 'English'), ('O', 'Other')], default='M', max_length=2, null=True),
        ),
    ]
