# Generated by Django 5.2.10 on 2026-02-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingdocument',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
