# Generated by Django 5.2.10 on 2026-01-27 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_number', models.CharField(max_length=20)),
                ('street_name', models.CharField(max_length=200)),
                ('unit_number', models.CharField(blank=True, max_length=20)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'The Smith Family'", max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='allergies',
            field=models.TextField(blank=True, help_text='JSON or text list of allergies'),
        ),
        migrations.AddField(
            model_name='client',
            name='dietary_restrictions',
            field=models.TextField(blank=True, help_text='JSON or text list of restrictions'),
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Other')], default='X', max_length=1),
        ),
        migrations.AddField(
            model_name='traveldocument',
            name='issuing_country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='clients.address'),
        ),
        migrations.AddField(
            model_name='client',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='clients.family'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('CC', 'Credit Card'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('OTHER', 'Other')], default='CC', max_length=10)),
                ('details', models.CharField(help_text="e.g. 'Visa ending 4242' or Account Number", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='clients.family')),
            ],
        ),
    ]
