# Generated by Django 5.2.10 on 2026-01-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_address_family_client_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='origin',
            field=models.CharField(blank=True, help_text='City, Country', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='preferred_language',
            field=models.CharField(choices=[('EN', 'English'), ('ZH', 'Mandarin'), ('MX', 'Cantonese')], default='ZH', max_length=2),
        ),
    ]
