# Generated by Django 5.2.10 on 2026-02-04 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_city_ethnicity_alter_client_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'John Doe Travel Partners'", max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Travel Groups',
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='family',
        ),
        migrations.RemoveField(
            model_name='paymentmethod',
            name='family',
        ),
        migrations.AddField(
            model_name='client',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='clients.travelgroup'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='travel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='clients.travelgroup'),
        ),
        migrations.DeleteModel(
            name='Family',
        ),
    ]
